"""Student Schema

Revision ID: 01f2ebf8a1cd
Revises: 
Create Date: 2024-06-29 15:45:56.741310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f2ebf8a1cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('nombre', sa.String(length=20), nullable=False),
        sa.Column('apellido', sa.String(length=20), nullable=False),
        sa.Column('identificacion', sa.String(length=10), nullable=False),
        sa.Column('edad', sa.Integer(), nullable=False),
        sa.Column('afinidad_magica', sa.String(length=20), nullable=False),
        sa.Column('grimorio', sa.String(length=25), nullable=False),
        sa.Column('estado', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('identificacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
